name: Run Selenium Tests Manually

# Trigger manually from GitHub Actions UI
on:
  workflow_dispatch:

jobs:
  selenium-tests:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full checkout for tests

      # Step 2: Set up .NET Core environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Step 3: Restore dependencies for Selenium test project
      - name: Restore dependencies
        run: dotnet restore ./SeleniumTests/SeleniumTests.csproj

      # Step 4: Build the Selenium test project
      - name: Build Selenium Test Project
        run: dotnet build ./SeleniumTests/SeleniumTests.csproj --configuration Release

      # Step 5: Run Selenium tests with the provided run settings file
      - name: Run Selenium Tests
        run: dotnet test ./SeleniumTests/bin/Release/net8.0/SeleniumTests.dll --settings AppTest.runsettings --logger:"trx;LogFileName=selenium.trx"

      # Step 6: Upload Selenium test results as an artifact
      - name: Upload Selenium Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Selenium-Test-Results
          path: ./SeleniumTests/TestResults/selenium.trx
