name: Run Selenium Tests Manually

on:
  workflow_dispatch:

jobs:
  selenium-tests:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up .NET Core environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Step 3: Set up Chromium and ChromeDriver
      - name: Set up Chromium and ChromeDriver
        uses: actions/setup-chromedriver@v4
        with:
          chromium-version: latest

      # Step 4: Restore dependencies for Selenium test project
      - name: Restore dependencies
        run: dotnet restore ./SeleniumTests/SeleniumTests.csproj

      # Step 5: Build the Selenium test project
      - name: Build Selenium Test Project
        run: dotnet build ./SeleniumTests/SeleniumTests.csproj --configuration Release

      # Step 6: Run Selenium tests with settings file and logger
      - name: Run Selenium Tests
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        run: dotnet test ./SeleniumTests/bin/Release/net8.0/SeleniumTests.dll --settings AppTest.runsettings --logger:"trx;LogFileName=selenium.trx"

      # Step 7: Upload Selenium test results as an artifact
      - name: Upload Selenium Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Selenium-Test-Results
          path: ./SeleniumTests/TestResults/selenium.trx

      # Step 8: Cleanup step
      - name: Cleanup workspace
        if: always()
        run: |
          rm -rf ./SeleniumTests/TestResults
