name: Run Selenium Tests Manually

on:
  workflow_dispatch:

jobs:
  selenium-tests:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Verify Chrome Version
        run: google-chrome --version

      - name: Restore dependencies
        run: dotnet restore ./SeleniumTests/SeleniumTests.csproj

      - name: Build Selenium Test Project
        run: dotnet build ./SeleniumTests/SeleniumTests.csproj --configuration Release

      - name: Run Selenium Tests
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        run: dotnet test ./SeleniumTests/bin/Release/net8.0/SeleniumTests.dll --settings AppTest.runsettings --logger:"trx;LogFileName=selenium.trx"

      - name: Upload Selenium Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Selenium-Test-Results
          path: ./SeleniumTests/TestResults/selenium.trx
