name: Run Selenium Tests Manually

on:
  workflow_dispatch:

jobs:
  selenium-tests:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up .NET Core environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Step 3: Install Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 4: Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          sudo apt-get install -y chromium-chromedriver

      # Step 5: Restore dependencies for Selenium test project
      - name: Restore dependencies
        run: dotnet restore ./SeleniumTests/SeleniumTests.csproj

      # Step 6: Build the Selenium test project
      - name: Build Selenium Test Project
        run: dotnet build ./SeleniumTests/SeleniumTests.csproj --configuration Release

      # Step 7: Run Selenium tests
      - name: Run Selenium Tests
        run: dotnet test ./SeleniumTests/bin/Release/net8.0/SeleniumTests.dll --logger:"trx;LogFileName=selenium.trx"

      # Step 8: Upload Selenium test results as an artifact
      - name: Upload Selenium Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Selenium-Test-Results
          path: ./SeleniumTests/TestResults/selenium.trx