name: SonarCloud

on:
  workflow_dispatch:

jobs:
  scan_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Project
        run: dotnet build BPCalculatorUnitTests.sln

      - name: Run Tests with Code Coverage
        run: dotnet test --collect "Code Coverage"

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=x00218712
            -Dsonar.projectKey=x00218712_testr
           
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
