name: "sonar_cloud_scan_github_actions"
on:
  workflow_dispatch:

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
        with:
            fetch-depth: 0
     
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
           
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=x00218712
              -Dsonar.projectKey=x00218712_testr
           
