name: SonarCloud Analysis

on:
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Step 3: Install SonarScanner globally
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      # Step 4: Add .NET Tools to PATH
      - name: Add .NET Tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Step 5: Begin SonarCloud Analysis
      - name: SonarCloud - Begin Analysis
        run: |
          dotnet sonarscanner begin \
            /o:"x00218712" \
            /k:"x00218712_testr" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

      # Step 6: Build the project
      - name: Build project
        run: dotnet build BPCalculator.sln --configuration Release

      # Step 7: Run tests and collect code coverage
      - name: Run tests and collect coverage
        run: dotnet test BPCaluatorUnitTests/BPCaluatorUnitTests.csproj \
          --configuration Release \
          --collect:"XPlat Code Coverage"

      # Step 8: End SonarCloud Analysis
      - name: SonarCloud - End Analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
