name: "SonarCloud_Scan_GitHub_Actions"
on:
  workflow_dispatch:

jobs:
  DemoSonarCloudScan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0' # Update this version based on your project requirements

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests and Collect Code Coverage
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Prepare SonarCloud Scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:/home/runner/.dotnet/tools"

      - name: Run SonarCloud Scan
        run: |
          dotnet sonarscanner begin \
            /k:"x00218712_testr" \
            /o:"x00218712" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.exclusions="**/Selenium/**,**/*Selenium*.cs" # Exclude Selenium files and directories
          dotnet build --no-restore --configuration Release
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
